import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import Midpanel from '../../components/Midpanel/Midpanel';
import Navbar from '../../components/Navbar';
function ChatHome() {
    return (
        <div>
            <Head>
                <title>ZCF | Chat</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.jpeg" />
            </Head>
            <main className="flex h-screen w-full">
                {/* Container wrapper */}
                <div className="flex w-full">
                    {/* Left navigation Panel */}
                        <Navbar active={true}/>
                    {/* Mid items panel */}
                        <Midpanel />
                    {/* Chat section */}
                    <div className="flex-grow w-1/2  bg-gray-50 h-screen p-5 text-white bg-gray-100 rounded-2xl"></div>
                </div>
            </main>
        </div>
    )
}

export default ChatHome
