import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'


export default function Register() {
  return (
    <div>
      <Head>
        <title>ZCF | Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpeg" />
      </Head>
        
      <main>
          {/* Container */}
          <div className="flex items-center">
            {/* Left section*/}
            <div className="w-full p-4 md:w-1/2  sm:px-20 md:px-56 rounded-full">
              <div className="grid justify-center">
                  <Image src="/logo.jpeg" alt="ZCF LOGO" height={200} width={200}/>
                </div>
              {/* <h1 className="font-bold text-[#198A00] text-4xl">ZCF Web</h1> */}
              <p className="w-full pt-10 text-4xl font-bold text-[#198A00]">Create an account</p>
              {/* <p className="text-[#198A00] pt-3 w-full">Be part of the best social experience.</p> */}
              <div className="items-center py-4">
                
                <form className="w-full">
                  <p className="pt-2 pb-2 text-gray-500">Username*</p>
                  <input type="text" className="flex w-full border-[#198A00] border p-4 rounded-full focus:outline-none transition duration-150 transform focus:border-2" placeholder="i.e johndoe100"/>
                  <p className="pt-6 pb-2 text-gray-500">Password*</p>
                  <input type="password" className="flex w-full border-[#198A00] border p-4 rounded-full focus:outline-none focus:border-[#198A00] transition duration-150 transform focus:border-2" placeholder="Min 8 Characters"/>

                  <div className="flex items-center">
                     <span className="mt-4 text-gray-500">Forgot Password?</span>
                  </div>
                  <button className="border-2 mt-2 w-full border-[#198A00] bg-[#198A00] border-2 p-4 rounded-full items-center text-white shadow-md transition duration-150 transform hover:shadow-xl">LOGIN</button>
                  
                </form>
                <div className="mt-4 mx-auto center">
                     <span className="mt-4 text-gray-500">Have an account? </span><Link href="/" className="text-[#198A00] font-bold cursor-pointer"><span className="text-[#198A00] font-bold">Login here</span></Link>
                  </div>
              </div>
            </div>
            {/* Right Section */}
            <div className="flex items-center flex-grow h-screen contrast-1 rounded-l-full shadow-2xl opacity-90 mix-blend-multiply bg-[#198A00]" 
              style={{ 
                    backgroundImage: `url("/assets/pexel (3).jpg")` ,
                    backgroundRepeat: 'no-repeat',
                    backgroundSize:'cover',
                    backgroundPosition: 'center',
                }}>
              <h1 className="justify-center"></h1>
              
            </div>
          </div>
      </main>
    </div>
  )
}
